name:                prehsept
version:             0.6.6.6
github:              "augustunderground/prehsept"
license:             BSD3
author:              "Yannick Uhlmann"
maintainer:          "augustunderground@pm.me"
copyright:           "Yannick Uhlmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            "PRECEPT, but in Haskell."
category:            "ML, EDA"

description:         Please see the README on GitHub at <https://github.com/augustunderground/prehsept#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- libtorch-ffi
- bytestring
- binary
- time
- directory
- optparse-applicative
- terminal-progress-bar
- text
- hvega
- ihaskell-hvega

library:
  source-dirs: src

executables:
  prehsept-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prehsept
    when:
    - condition: false
      other-modules: Paths_prehsept

tests:
  prehsept-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prehsept
