resolver: lts-18.28 #lts-18.6
compiler: ghc-8.10.7 #ghc-8.10.4

packages:
- .

ghc-options:
  "$locals": -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 # -v

apply-ghc-options: locals

extra-deps:
  - git: https://github.com/hasktorch/hasktorch.git
    commit: d77e48c6ab7b356c0ad480f00b9092cb49f5a37f
    subdirs:
      - hasktorch
      - libtorch-ffi
      - libtorch-ffi-helper
  - ihaskell-hvega-0.3.2.0@sha256:57b749f3c14b224af6f9484b2cd531299dd740477aa6e6f300f19a8c291b5fac,1182

extra-include-dirs:
  - libtorch/include/torch/csrc/api/include
  - libtorch/include

extra-lib-dirs:
  - ./libtorch/lib
